name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Setup pnpm via action
        uses: pnpm/action-setup@v2
        with:
          version: 'latest'
      - name: Install dependencies
        run: pnpm install
      - name: Run lint
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: pnpm -s exec eslint .
      - name: Run typecheck
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: pnpm -s exec tsc --noEmit
      - name: Run tests
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: pnpm -s exec vitest run
